---
#main.yml

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Enable universe repository
  apt_repository:
    repo: '{{ item }}'
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"  
    - "deb https://download.docker.com/linux/ubuntu bionic stable"

- name: install nginx, mc, setools, auditd
  yum:
    name: 
        - audit
        - mc
        - nginx
        - setools-console
        - policycoreutils-python
        - policycoreutils-newrole
        - selinux-policy-mls
    state: present
      
- include: 03_setup_users.yml 
