# - name: Pull default Docker image
#   docker_image:
#     name: shamelesscookie/nginx:latest
#     source: pull

# Creates the number of containers defined by the variable create_containers, using values from vars file
- name: Create & start nginx container with apparmor
  docker_container:
    name: apparmor-nginx
    image: nginx
    security_opts: "apparmor={{ policy_for_docker_nginx }}"
    ports: "8880:80"
    state: started
