- name: install required packages(auditd)
  apt: 
    update_cache: no 
    name: auditd
    state: latest

- name: copy auditd rules
  copy:
      src: 'audit/audit.rules'
      dest: "/etc/audit/rules.d/audit.rules"
      owner: root
      group: root
      mode: 0644

- name: restart auditd
  service:
    name: auditd
    state: restarted      