# -*- mode: ruby -*-
# vi: set ft=ruby :

    Vagrant.configure("2") do |config|
        config.vm.synced_folder '.', '/vagrant', disabled: true
#        config.ssh.username = 'vagrant'
#        config.ssh.password = 'vagrant'
        config.vm.define "ub1404" do |ub1404|
          ub1404.vm.box = "rapid7/metasploitable3-ub1404"
          ub1404.vm.hostname = "metasploitable3-ub1404"
          ub1404.vm.network "private_network", ip: '10.0.0.51', virtualbox__intnet: "netb"

          ub1404.vm.provider "virtualbox" do |v|
            v.name = "Metasploitable3-ub1404"
            v.memory = 1024
          end
        end
        config.vm.define "kalihw06" do |kbox|
          kbox.vm.box = "kalilinux/rolling"
          kbox.vm.hostname = "kalihw06"
          kbox.vm.network "private_network", ip: '10.0.0.52', virtualbox__intnet: "netb"

          kbox.vm.provider "virtualbox" do |v|
            v.name = "kalihw06"
            v.memory = 1024
            v.gui=false
          end
        end
    end
