---
- hosts: all
  remote_user: vagrant
  tasks:
  - name: Install apache2 web server
    yum: name=httpd state=latest

  - name: ensure apache is running
    service:
        name: httpd
        state: started
        enabled: yes
    notify: 
    - startservice
    
  handlers:
  - name: startservice
    service: 
        name: httpd
        state: restarted
