# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION=2

CONFIG_FILE='boxes_config.yml'
require='yaml'
myRoot=File.dirname(__FILE__)
if not Pathname(myRoot + "/" + CONFIG_FILE).exist?
    fail "vagrant.yml not found"
end

vagrantCfg=YAML.load_file(myRoot + "/" + CONFIG_FILE)
node_cpus=vagrantCfg['global']['cpus']||1
node_mem=vagrantCfg['global']['mem']||1024

node_ip_pattern=vagrantCfg['global']['ip_pattern']||'192.168.254.'

box_number=1

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    box_count=0

    vagrantCfg['boxes'].each do |boxName, boxCfg|
        box_count+=1
    end    

    hostList=Hash.new

    vagrantCfg['boxes'].each do |boxName, boxCfg|
        host_name=boxName#+'.local'
        host_ip="#{node_ip_pattern}%d" % box_number
        hostList[boxName]={'host'=>host_name,'ip'=>host_ip}
        box_number+=1
    end    

    vagrantCfg['boxes'].each do |boxName, boxCfg|
        box_name=boxName
        host_name=hostList[boxName]['host']
        host_ip=hostList[boxName]['ip']
        bx=boxCfg['box']
        config.vm.define box_name do |box|
            box.vm.box=bx['box']
            box.vm.hostname=host_name
            box.vm.network :private_network, ip: host_ip

            box.vm.provision "shell", path: "bootstrap.sh", privileged: true, args: "#{bx['default_root']}"

            box.vm.provision :hosts do |hosts|
                hostList.each do |host_name, host_item|
                    hosts.add_host host_item['ip'], [host_item['host']]
                end
            end        


            box.vm.provider "virtualbox" do |vbox|
                vbox.memory=node_mem
                vbox.cpus=node_cpus
            end
        end

    end
end                

