- name: create policy dir for apparmor if not exists
  file:
    path: '/etc/apparmor.d/{{aa_policy_dir}}'
    state: directory
    mode: 0755
    group: root
    owner: root

- name: copy apparmor policy
  copy:
    src: "{{ local_policy_path_for_docker_nginx}}/{{ policy_for_docker_nginx }}"
    dest: "/etc/apparmor.d/{{ aa_policy_dir }}"
    owner: root
    group: root
    mode: 0644

- name: apparmor | enable apparmor profile for docker nginx 
  command: "apparmor_parser -r -W /etc/apparmor.d/{{ aa_policy_dir }}/{{ policy_for_docker_nginx }}"
