# - name: prevent user otus2 to login using ssh
#   lineinfile:
#     path: /etc/pam.d/remote
#     regexp: ^account required pam_time.so
#     line: account required pam_time.so
#     state: present
  
- name: prevent user otus2 to login using ssh
  pamd:
    name: sshd
    type: account
    control: required
    module_path: pam_nologin.so
    new_type: account
    new_control: required
    new_module_path: pam_time.so
    state: after
  
- name: prevent user otus2 to login using ssh
  blockinfile:
    path: /etc/security/time.conf
    block: |
      *;*;otus2;!Al000-2400


- name: restart sshd
  service:
    name: sshd
    state: restarted      
