# -*- mode: ruby -*-
# vi: set ft=ruby :

$n1_ip1="192.168.99.100"
$n1_host="node1.local"

$n2_ip1="192.168.99.101"
$n2_ip2="172.16.99.101"
$n2_host="node2.local"

$n3_ip1="192.168.99.102"
$n3_ip2="172.16.99.102"
$n3_host="node3.local"

bootstrap = <<SCRIPT
  useradd -m testuser1; echo -e "testtest\ntesttest" | passwd testuser1
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.define "node1", primary: true do |n1|
        n1.vm.box="centos/7"
        n1.vm.hostname=$n1_host
        n1.vm.network "private_network", ip: $n1_ip1

        n1.vm.provision :hosts do |hosts| 
            hosts.add_host $n1_ip1, [$n1_host]
            hosts.add_host $n2_ip1, [$n2_host]
            hosts.add_host $n3_ip1, [$n3_host]
        end

        n1.vm.provision "shell", inline: "#{bootstrap}", privileged: true

        n1.vm.provider "virtualbox" do |vbox|
            vbox.memory=1024
            vbox.cpus=1
        end
    end

    config.vm.define "node2", primary: true do |n2|
        n2.vm.box="centos/7"
        n2.vm.hostname=$n2_host
        n2.vm.network "private_network", ip: $n2_ip1
        n2.vm.network "private_network", ip: $n2_ip2, virtualbox__intnet: "remotenw"

        n2.vm.provision :hosts do |hosts| 
            hosts.add_host $n1_ip1, [$n1_host]
            hosts.add_host $n2_ip1, [$n2_host]
            hosts.add_host $n3_ip1, [$n3_host]
        end

        n2.vm.provision "shell", inline: "#{bootstrap}", privileged: true

        n2.vm.provider "virtualbox" do |vbox|
            vbox.memory=1024
            vbox.cpus=1
        end
    end

    config.vm.define "node3", primary: true do |n3|
        n3.vm.box="centos/7"
        n3.vm.hostname=$n3_host
        #n3.vm.network "private_network", ip: $n3_ip1
        n3.vm.network "private_network", ip: $n3_ip2, virtualbox__intnet: "remotenw"

        n3.vm.provision :hosts do |hosts| 
            hosts.add_host $n1_ip1, [$n1_host]
            hosts.add_host $n2_ip1, [$n2_host]
            hosts.add_host $n3_ip1, [$n3_host]
        end

        n3.vm.provision "shell", inline: "#{bootstrap}", privileged: true

        n3.vm.provider "virtualbox" do |vbox|
            vbox.memory=1024
            vbox.cpus=1
        end
    end    
end