---
- name: check nginx works fine (curl http://localhost:{{ nginx_port }}/)
  block:  
    - name: shell command curl  
      shell: 
        cmd: 'curl http://localhost:{{ nginx_port}}/'
        warn: no
      register: nginx_test_results
  rescue:
    - name: msg if failed
      shell: 
        cmd: 'echo "nginx test failed ({{ nginx_custom_port_selinux_mode }})"'
      register: nginx_test_results

  
- name: output test result
  debug:
    msg: "{{ nginx_test_results.stdout }}  ({{ nginx_custom_port_selinux_mode }})"


